## conda requirements for all packages needed to run the scanpy tutorials
# install with:  mamba env create -n spatial2022 -f environment_spatial2022.yml
# then run: source activate spatial2022
name: spatial2022

channels:
### MAIN CONDA CHANNELS ###
 - conda-forge
 - anaconda
 - bioconda
 - defaults
 - r
### ADDITIONAL CONDA CHANNELS ###
 - rdonnelly
 - psi4
 - r_test
 - free
 - fastchan
 - ccordoba12
 - grst
 - Eugene_T
 - letaylor
 - ohsu-comp-bio

dependencies:
### PYTHON LIBRARIES ###
 - compilers
 - notebook
 - jupyter_contrib_nbextensions
 - jupyter_client
 - nbconvert
 - pandoc
 - python-annoy
 - multicore-tsne
 - requests
 - python-annoy
 - mnnpy
 - scanpy
 - scanorama
 - numba
 - llvmlite
 - python-igraph
 - umap-learn
 - louvain
 - leidenalg
 - matplotlib-venn
 - scrublet
 - gseapy
 - pybiomart
 - squidpy
 - morphops
 - pip
 - pip:
   - gsea-api

