name: spatial2022

channels:
 - conda-forge
 - anaconda
 - bioconda
 - defaults
 - r
 - rdonnelly
 - psi4
 - r_test
 - free
 - fastchan
 - ccordoba12
 - grst
 - Eugene_T
 - letaylor
 - ohsu-comp-bio

dependencies:
 - python=3.9
 - compilers
 - notebook
 - jupyter_contrib_nbextensions
 - jupyter_client
 - nbconvert
 - pandoc
 - python-annoy
 - multicore-tsne
 - requests
 - python-annoy
 - mnnpy
 - scanpy
 - scanorama
 - numba
 - llvmlite
 - python-igraph
 - umap-learn
 - louvain
 - leidenalg
 - matplotlib-venn
 - scrublet
 - gseapy
 - pybiomart
 - squidpy
 - morphops
 - napari
 - pip
 - pip:
   - gsea-api
   - tissuumaps[full]
   - eggplant
   - git+https://github.com/ludvb/xfuse@master
