name: spatial2022

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.9
  - tree
  - compilers
  - notebook
  - jupyter_contrib_nbextensions
  - jupyter_client
  - nbconvert
  - pandoc
  - multicore-tsne
  - requests
  - python-annoy
  - scvi-tools
  - mnnpy
  - scanpy
  - scanorama
  - numpy=1.21.6
  - numba
  - python-igraph
  - umap-learn
  - louvain
  - leidenalg
  - matplotlib-venn
  - scrublet
  - gseapy
  - pybiomart
  - squidpy>=1.2.2
  - morphops
  - napari
  - starfish
  - libvips
  - pip
  - pip:
      - git+https://github.com/ludvb/xfuse@master
      - gsea-api
      - tissuumaps[full]
      - git+https://github.com/czarnewski/eggplant@master
      - psfmodels
      - planktonspace
      - numpy==1.22.4
